### ISSUE TITLE
exist deployment incomplete

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#111]
When deploying a develop-branch build to eXist-db 3.2 The following error is produced

```shell
Deployment incomplete, 1 issues found: OpenSans-ExtraBoldItalic-webfont.svg: The XML parser reported a problem: fatal error at (-1,-1) : Premature end of file.
```

and the respective file is not being deployed to the database.

**Comment by bwbohl** [comment]
In fact the source file is empty, at 
`packages/eoTheme/resources/fonts/OpenSans/OpenSans-ExtraBoldItalic-webfont.svg`

**Comment by krHERO** [comment]
@bwbohl still an issue?

**Comment by bwbohl** [comment]
referring to really old version of both eXist-db and Edirom Online. The current release and dev builds deploy just fine, thus closing.
