### ISSUE TITLE
Improve citability

### ISSUE THREAD

**Issue by roewenstrunk** [Edirom/Edirom-Online#113]
The Release should be citable as decribed here: https://guides.github.com/activities/citable-code/

**Comment by bwbohl** [comment]
fetch contributor names over github api

**Comment by bwbohl** [comment]
The GitHub repo is archived and published through Zenodo at [10.5281/zenodo.5347861](https://zenodo.org/doi/10.5281/zenodo.5347861). This is a good start, nonetheless I think there is room for improvement:

- [ ] Add the all version DOI to README
- [ ] Add the release-specific DOIs to all Releases published at Zenodo
- [ ] Improve the metadata of the Zenodo publications (maybe a CFF file as mentioned above might help)
- [ ] Add build artifacts to the Zenodo publications

**Comment by daniel-jettka** [comment]
> fetch contributor names over github api

https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-contributors

**Comment by daniel-jettka** [comment]
>     * [ ]   Add a citation proposal for citation of unreleased branches

Adding a citation section to README which says one shall add the commit hash to the citation... not sure if that's sufficient

**Comment by daniel-jettka** [comment]
>     * [ ]  Add build artifacts to the Zenodo publications

Isn't that fulfilled by default? All versions with DOIs are listed on right hand side in Zenodo:

![image](https://github.com/user-attachments/assets/75b6e9e7-22cf-4df0-9845-4479d84ab4d8)

**Comment by daniel-jettka** [comment]
>     * [ ]  Add build artifacts to the Zenodo publications

How?

**Comment by daniel-jettka** [comment]
ping @bwbohl :-)

**Comment by daniel-jettka** [comment]
separate issue for Zenodo problem / features moved to: #475 

We will create a pull request for the present issue now.

**Comment by daniel-jettka** [comment]
> > ```
> > * [ ]  Add build artifacts to the Zenodo publications
> > ```
> 
> How?

For 1.0.0-beta.6 the xar was added manually because the complete publication in Zenodo was manually
https://zenodo.org/records/14196509

**Comment by bwbohl** [comment]
> > ```
> > * [ ]  Add the release-specific DOIs to all Releases published at Zenodo
> > ```
> 
> Isn't that fulfilled by default? All versions with DOIs are listed on right hand side in Zenodo:
> 
> ![image](https://private-user-images.githubusercontent.com/18614293/382302051-75b6e9e7-22cf-4df0-9845-4479d84ab4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTkyMjEsIm5iZiI6MTczNDYxODkyMSwicGF0aCI6Ii8xODYxNDI5My8zODIzMDIwNTEtNzViNmU5ZTctMjJjZi00ZGYwLTk4NDUtNDQ3OWQ4NGFiNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE0MzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OWFjZDIyMmQwNzBiNjc5NWIxNWY5NTI4ZGZjYzI2NWRmNDJlNzg5NTNjMTJjYjk0YWFlZmQ0NzkyOGFhOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dlg9LkTVl0nXzpBtOcmck6vEtBRArAJDqCkDXxet_P4)

I didn’t mean on Zenodo but either in the Release description and/or in the code, e.g., in the About window or in the expath-pkg.xml (don’t know if thats possible) or at least in some version.txt in the package.
