### ISSUE TITLE
fullwidht apostrophe  – Window fails to load

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#118]
When a fullwidth Apostrophe »'« (U+FF07) is part of the value being evaluated as window title the resource . fails to load

**Comment by peterstadler** [comment]
can you elaborate a little bit, please? Which XQuery(?) function fails?

**Comment by bwbohl** [comment]
Apparently this is quite old and probably also connected to #337

By the time I reported these content windows in the Edirom Online GUI failed to load contents and loaded as empty blank windows. All this was because the window title had some unexpected character, e.g. apostrophe (tick) or newline character. Probably normalizing space or even the proper serialization of requests might fix those issues.

**Comment by riedde** [comment]
The same for me, I also can't reproduce this. @bwbohl would you share a file with me that produces the fail? Maybe the problem is caused by a different incident.

**Comment by peterstadler** [comment]
I really do think this issue is outdated and fixed by proper serialization. I propose to close the issue if we do not come up with a reproducible test case in the next week

**Comment by bwbohl** [comment]
It

> The same for me, I also can't reproduce this. @bwbohl would you share a file with me that produces the fail? Maybe the problem is caused by a different incident.

The issue is so 2017 ;-). I really don't think I still have the file lying around. So, I'm +1 for closing this as it is not reproducible.

**Comment by bwbohl** [comment]
@thx for all your efforts @riedde & @peterstadler
