### ISSUE TITLE
[ftr] Go to… menu in parts

### ISSUE THREAD

**Issue by roewenstrunk** [Edirom/Edirom-Online#13]
While going to the page displaying the beginning of a movement or number in scores is easy, we need to have an extra layer for parts in part books.

**Comment by roewenstrunk** [comment]
There is an edition where we implemented a sub structure for parts in "Go to" menu. But this doesn't seem to be in the core repo.

**Comment by feuerbart** [comment]
I copied the parts from the OPERA-implementation and was able to make it work. tested with open-faust sources A3 (with parts) and A2 (without parts).
OPERAs code was never finished, i guess. looks like there is an implementation of partwise and movementwise, but the latter was never finished. probably going to rework it the next days.

see: [9617525](https://github.com/feuerbart/Edirom-Online/commit/9617525cc03bf920969cb540b6993df7442d6481)

**Comment by bwbohl** [comment]
You’re correct to assume that the `movementwise` display was never finished. That was because the decision was to use the `partwise` exclusively in OPERA. But making it work would be great. Maybe there should be a prefs entry for that?

**Comment by feuerbart** [comment]
#493 should solve this issue.

**Comment by krHERO** [comment]
should #493 also close #101

**Comment by feuerbart** [comment]
yes, #101 is basically the same issue.
