### ISSUE TITLE
util:serialize not defined

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#135]
<path>/db/apps/EdiromOnline/data/xql/getAnnotationsOnPage.xql</path>
<message>err:XPST0017 Function util:serialize() is not defined in module namespace: http://exist-db.org/xquery/util [at line 120, column 21]</message>

tested with eXist-db 5.20 and Shared Resources 0.8.4

**Comment by bwbohl** [comment]
the referenced module is part of the exist-core, or rather was…
A new function should be found to replace this call AND eXist-sb should be added as dependency in the expats-pkg.xml, e.g.:
```xml
<dependency processor="http://exist-db.org" semver-min="3.5.0"/>
```

**Comment by bwbohl** [comment]
maybe `util:eval-and-serialize` does the trick?

**Comment by bwbohl** [comment]
probably connected to 80afeebe59e1b7228b8a27233007501d09883e5a

**Comment by bwbohl** [comment]
closed with 2587c66b286f2297434f5407352f51261f4a8961

**Comment by nikobeer** [comment]
See https://github.com/Max-Reger-Institut/Edirom-Online/commit/83cc5a1526cb910f201d57c992833026ad71e9ff

**Comment by bwbohl** [comment]
util:eval-and-serialize will for sure work, nevertheless I consider it a bit over the top compared to fn:serialize() which also does the job.
