### ISSUE TITLE
Check english and german language files

### ISSUE THREAD

**Issue by roewenstrunk** [Edirom/Edirom-Online#154]
Check if the english and german language files have equal entries.

**Comment by bwbohl** [comment]
Schematron could be very useful here.

**Comment by peterstadler** [comment]
It'd probably quite easy to add a test to the GitHub actions to check for this issue (be it schematron or what have you).

On the other hand that would not help customizations of the Edirom where users might alter those dictionaries or even provide their own (I assume this is possible)? So maybe we should even run this check at startup and output a warning if some misalignment was found?

**Comment by peterstadler** [comment]
I'm volunteering to implement such a test but still need some guidance on where and when to run such a test:

* when installing Edirom Online, i.e. as a post-install-script within eXist?
* when building Edirom Online, i.e. as part of the (yet to be implemented) test suite? (This would allow to test this locally as well as on any CI/CD system)

**Comment by roewenstrunk** [comment]
Hi @peterstadler, Ideally, we would have two tests. When the Edirom is built, we can only test the information that is delivered with the Edirom or the information that is built in via a fork. We often also allow project-specific customizations through information in the data packages, but these are not available neither when building nor when installing the Edirom. It might be a good idea to offer tests for data packages here.
I would suggest that we first start with a test when building the Edirom. This can then also be offered stand-alone for data packets. What do you think?

**Comment by bwbohl** [comment]
We could decide on whether to have the schematron for this in the https://github.com/Edirom/edirom-edition-schema repository then it could be used 'idendependently'.

The fist aim could be to just check the lang files when editing them, e.g. by referencing the schematron from the files. Checking this on build seems like a good idea. Additionally we could add a GitHub Action that performs the check when any of the files gets modified in a PR to assure that all languages cover all terms e.g. in case something get added or removed.

For data packages the tricky part is they don’t have to provide full coverage of all language variables but might just provide those that should be overridden. The Edirom Online uses its default language files as fallback in those cases.
