### ISSUE TITLE
SearchWindow: Use edition path for collection function

### ISSUE THREAD

**Issue by roewenstrunk** [Edirom/Edirom-Online#156]
https://github.com/Edirom/Edirom-Online/blob/develop/add/data/xql/search.xql at the moment queries the database root (/db) collection; thus it returns result from outside the current edition context

**Comment by peterstadler** [comment]
Is there a canonical function for retrieving the edition context? Is this somehow related to #83

**Comment by hizclick** [comment]
@roewenstrunk, Kun je daar wat dieper op ingaan?

**Comment by bwbohl** [comment]
@hizclick this is basically about the hard coded paths in

https://github.com/Edirom/Edirom-Online/blob/91abe6bf70d80b886a1cdb8240419b83d0396af5/add/data/xql/search.xql#L76-L85

Looking at these the collection that is being queried is '/db' – the whole database. This of course might make sense in some context (e.g., when an Edirom deployment only includes one edition of one work). But, e.g., if you have multiple editions installed the search will also return hits from those.

**Comment by bwbohl** [comment]
@peterstadler 

No there is not but there definitely should be! Such a function could be useful in many places in the Edirom Online.
