### ISSUE TITLE
Use AJAXController where possible

### ISSUE THREAD

**Issue by roewenstrunk** [Edirom/Edirom-Online#157]
* app/controller/navigator/Navigator.js

**Comment by bwbohl** [comment]
might be connected to #80 and #387

**Comment by bwbohl** [comment]
@roewenstrunk could you explain a bit on your initial idea behind the issue?

**Comment by roewenstrunk** [comment]
Hi @bwbohl, all,

The AJAXController provides a function `doAJAXRequest` (see https://github.com/Edirom/Edirom-Online/blob/d3f4ce45220f9d30c42d632eec43b7c9fc5a461b/app/controller/AJAXController.js#L40). This function provides some mechanisms that are useful with AJAX requests. You could define a retry limit (default is 2 retries), you could switch to a synchronous request (which you actually should not do), it automatically adds the current edition ID and the lang parameter to all requests.

You can see the usage for example here: https://github.com/Edirom/Edirom-Online/blob/d3f4ce45220f9d30c42d632eec43b7c9fc5a461b/app/controller/LinkController.js#L159

As far as I ca see, there is no old code without the AJAXController left. So this issue could be closed. I assume.

**Comment by bwbohl** [comment]
Thanks for clarifying; I just wanted to ensure we’re on the same page. I also think that we have covered this in the meantime. Moreover, it found its way to the https://github.com/Edirom/Edirom-Online/blob/develop/STYLE-GUIDE.md#javascript
