### ISSUE TITLE
revisit eutil:getLocalizedName

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#162]
What if the $node contains localised variants, this function would return both, wouldn't it?
Shouldn't there be a more general fallback first, e.g. something like:

Probably it should be clarified that not the node's but it's child nodes' values will be returned?

what string?

feel free to add `@author`

**Comment by bwbohl** [comment]
probably also rename util.xqm  file from to eutil.xqm for consistency's sake.

**Comment by riedde** [comment]
@riedde See also #311 #103  (PR #426), when revisiting

**Comment by bwbohl** [comment]
For 1.0.0 test in context of #426 close if fixed else push
