### ISSUE TITLE
edition prefs cant override image server and prefix

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#165]
must be done in edirom-prefs.xml, but in the times of IIIF servers being hosted by the preserving intitutions even a single eidtion might have to pull from differet locations. This should be modified.

**Comment by bwbohl** [comment]
apparently this was a combination of problems:

1. a faulty path to the prefs.xml [fixed now]
2. the getPreference function in EdiromOnline.controller.PreferenceController is very strict and returns `null` if the preference is set to an empty string

this probably should be fixed either by:

* providing a test for sempty string, e.g.  `if (me.preferences[key] == '')` or `if (me.preferences[key] == '' && lax)` alternatively. While the first would allow any preference to be empty without raising an error, the latter would provide the possibility of only allowing it whne specified in the call. @roewenstrunk  @riedde  @nikobeer  what do you prefer?

**Comment by riedde** [comment]
I'm not sure if i got it. For me it would be important that the empty value is allowed and able to override the default value given in edirom_prefs. Do we need to have empty values within other preferences?

**Comment by bwbohl** [comment]
not sure if we need it in other prefs I could also implement it just for image_prefix

**Comment by bwbohl** [comment]
I close this in favour of #164
