### ISSUE TITLE
Remove RWA logo from `#HomeBtn`

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#168]
and the corresponding image from the pix folder.

It would be nice to add something edirom:ish there

**Comment by riedde** [comment]
What about the ViFE logo? I mean the green one we also use for the summer school? We should discuss that at the next meeting.

**Comment by bwbohl** [comment]
or the blue one? as for vife in general?

**Comment by bwbohl** [comment]
I guess this duplicates #159 to some degree @roewenstrunk ?
