### ISSUE TITLE
show measures in measureBasedView

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#196]
measureBased view show measure numbers fails

**Comment by riedde** [comment]
I have tested it with the example edition and it worked @bwbohl. (I used the code in branch rel_100alpha)

**Comment by bwbohl** [comment]
closed with [d4cbf48](https://github.com/Edirom/Edirom-Online/commit/d4cbf48c5aa266dd80434c15d6f820fd7d1eb0bc)
