### ISSUE TITLE
remove index.html

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#202]
as we now use `index.xql` consequently `index.html` is deprecated an should be removed

**Comment by riedde** [comment]
@bwbohl Is that issue done?

**Comment by bwbohl** [comment]
hm, yes but apparently removing index.html raises errors with the build. Although the build runs fine, the installed Edirom-Online will not work properly. Probably will have to restore it, exclude it from packaging to xar and add som post-build action that pulls the contents of index.html to index.xql or similar. Maybe Sencha Cmd even support using a different filetype?

**Comment by riedde** [comment]
The controller would also work if we forward the url directly to index.xql, but that will not solve the sencha build problem.

For this release we should keep the index.html and terminate this issue to the v1.0.0-beta release.
