### ISSUE TITLE
CSS Styling of Measure Count

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#205]
* center position
* lighter appearance as in previous release

**Comment by bwbohl** [comment]
I mean the measure numbers that are being superimposed in the imageView. Moreover they should also trigger the measure-zone highlight in the facsimile.

**Comment by bwbohl** [comment]
> Moreover they should also trigger the measure-zone highlight in the facsimile.

Actually this is already the case but the CSS-layering an positioning is the problem to some degree, i.e., when the measure label overlaps with the zone of another measure that part of the label will not respond to the mouse-hover.

**Comment by riedde** [comment]
@nikobeer Could you fix the position of the measure label? I remember you said that you know how to do so. We will need this for some further tests. Thanks!
