### ISSUE TITLE
content height does not fit to window heigth

### ISSUE THREAD

**Issue by riedde** [Edirom/Edirom-Online#210]
the content is limited to a small div but scrollable. The content does not fit to the window heigth.

relates to #193

**Comment by bwbohl** [comment]
This is in the rendering view, right?
It's just a small CSS issue and I think @roewenstrunk is already working on the fix, right?

**Comment by roewenstrunk** [comment]
This issue is fixed with commit 9f1d65ceb14288494f8ae0972fa5d02b4fdbfa15.
Please review.

**Comment by bwbohl** [comment]
fix with rendering view #215
