### ISSUE TITLE
display edirom release or version number in GUI

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#213]
self explaining

**Comment by bwbohl** [comment]
connected to #381

**Comment by krHERO** [comment]
> connected to #381

thanks benni, @daniel-jettka and. decided to have this info (only) in the about (see #381), since it has to be placed here anyway. a lot of other software, eg browserss or apps have it in the "about", but not visible in the GUI. 
we will try to get this done soon

**Comment by daniel-jettka** [comment]
solved by #479
