### ISSUE TITLE
Rendering view fails

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#215]
On the `develop` branch some changes have been made to the verovio rendering view. On standard eXist-db deployment, the view now fails due to several reasons:

1. absolute paths to `resources/…`
2. missing `setMovements` function in JS
3. Absolute path when calling `getMusicInMdiv.xql`

**Comment by bwbohl** [comment]
@riedde please prepare a fix as PR against develop

**Comment by riedde** [comment]
I have added a util function for getting the application base path. This is now also passed to the verovio engine. Could you @roewenstrunk please have a look on the "missing setMovements function in JS" @bwbohl [mentioned](https://github.com/Edirom/Edirom-Online/issues/215#issue-1222293526)?
The PR https://github.com/Edirom/Edirom-Online/pull/220 contains all my chances, so the last fix could be done there.
