### ISSUE TITLE
Set up contribution guidelines

### ISSUE THREAD

**Issue by riedde** [Edirom/Edirom-Online#227]
- how to contribute
- gitflow documentation
- commit message templates/patterns
- ...

**Comment by krHERO** [comment]
also see #359 and current [CONTRIBUTING.md](CONTRIBUTING.md)
would like to add to your list
* issue template

**Comment by bwbohl** [comment]
you mean [CONTRIBUTING.md](https://github.com/Edirom/Edirom-Online/blob/develop/CONTRIBUTING.md)

**Comment by krHERO** [comment]
> also see #359 and current [CONTRIBUTING.md](https://github.com/Edirom/Edirom-Online/blob/develop/CONTRIBUTING.md) would like to add to your list
> 
> * issue template

already added issue templates with [PR395](https://github.com/Edirom/Edirom-Online/pull/395)
