### ISSUE TITLE
Edirom-Online fails if edition name cannot be found

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#233]
```
exerr:ERROR The actual return type does not match the sequence type declared
in the function's signature: edition:getName(xs:string) xs:string.
Expected cardinality: exactly one, got 0. [at line 121, column 33, source: 
/db/apps/Edirom-Online/index.xql] In function:
edition:getName(xs:string) [39:45:/db/apps/Edirom-Online/data/xqm/edition.xqm]
```

**Comment by bwbohl** [comment]
This also happens if no edition package is installed on the database. We should provide a prettified error report, maybe in the context of the splash screen designed for the case of multiple editions having been installed.

**Comment by bwbohl** [comment]
![Image](https://github.com/user-attachments/assets/eb8bea4b-cc6c-4349-ac40-99c17b8d5df2)

This is what happens if no edition is installed in the database.
As the screenshot shows, the error is really ugly and first gives the impression there might be something wrong with the code. I thin we should really try fix this for 1.1.0 and capture it nicely.

**Comment by daniel-jettka** [comment]
Has this been worked on in the meantime?! Because this is what I get:

![Image](https://github.com/user-attachments/assets/99245283-8e40-4845-8453-0648fd02f0ba)

**Comment by bwbohl** [comment]
Wow, that would be aweseome!

**Comment by bwbohl** [comment]
I can confirm t hat this is indeed fixed.
