### ISSUE TITLE
add legacy support for Euryanthe font

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#282]
Older Ediroms used the in-house developed Euryanthe font. In the sense of easier migration to Edirom Online we should integrate the Euryanthe font into Edirom Online.

**Comment by roewenstrunk** [comment]
Euryanthe font in https://github.com/Edirom/EuryantheFont available. Needs to be integrated in this repo.

**Comment by bwbohl** [comment]
- [ ] add a submodule to this repo
- [ ] include the font in the build process
- [ ] add `@font-face` to CSS

**Comment by bwbohl** [comment]
closed with #286
