### ISSUE TITLE
ftr: part default selection by encoding

### ISSUE THREAD

**Issue by riedde** [Edirom/Edirom-Online#293]
Add a conditional to getParts.xql for setting parts visibility to default false, if encoded so.
Usecase: Multiple handwritten parts (e.g., 3 times Violin I) but only one should be shown by default.

**Comment by bwbohl** [comment]
What about switching to https://github.com/music-addressability/ema/issues for such links in Edirom Online?

**Comment by riedde** [comment]
If I remember right, I've done this within #294 and #300
