### ISSUE TITLE
upload build artifacts on own PRs only

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#312]

**Comment by musicEnfanthen** [comment]
@bwbohl Seems to have been fixed already in https://github.com/Edirom/Edirom-Online/commit/b55b5c6a908e7beb08e50d026fda002fffcde642?

https://github.com/Edirom/Edirom-Online/blob/28d5e8b0a0e9603fc0627b35692fbfc04b7d2730/.github/workflows/docker-ci.yml#L33

**Comment by bwbohl** [comment]
@musicEnfanthen thx for the hint, missed to close this one with b55b5c6
