### ISSUE TITLE
Remove TextGrid functionality

### ISSUE THREAD

**Issue by DennisFriedl** [Edirom/Edirom-Online#322]
For example loginToTextGrid.xql and checkTextGridLogin.xql

**Comment by peterstadler** [comment]
there are also references to textgrid here https://github.com/Edirom/Edirom-Online/blob/52a8c2f81b19f12648cc5263388e094ed441357d/add/data/xqm/util.xqm#L138-L149 and here https://github.com/Edirom/Edirom-Online/blob/52a8c2f81b19f12648cc5263388e094ed441357d/app/controller/LinkController.js#L119-L120

I think this should also be removed?

**Comment by bwbohl** [comment]
although d44dfd080d82da253d211cc3d9480f720fa9c52e removed the xql files the code references above probably should be revisited

**Comment by bwbohl** [comment]
@DennisFriedl can you take care of this?
