### ISSUE TITLE
Remove getAnnotationParticipants.xql

### ISSUE THREAD

**Issue by Diginaut** [Edirom/Edirom-Online#324]
Deprecated module.

**Comment by bwbohl** [comment]
could you please elaborate a bit: why is this outdated?

**Comment by krHERO** [comment]
ping @Diginaut

**Comment by bwbohl** [comment]
yeah it’s not referenced

**Comment by bwbohl** [comment]
closed with d44dfd080d82da253d211cc3d9480f720fa9c52e
