### ISSUE TITLE
[ftr] Implement Styleguide

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#336]
For easier future maintenance and development, we should introduce style guidelines for the different (programming) languages used in Edirom Online:

- [ ] **JavaScript** Maybe something by Sencha or https://google.github.io/styleguide/jsguide.html
- [ ] **CSS** Recommendation: https://google.github.io/styleguide/htmlcssguide.html
- [ ] **SCSS**
- [ ] **XSLT**
- [ ] **XQuery** Recommendation: http://xqdoc.org/xquery-style.pdf
- [ ] **HTML**

**Comment by kepper** [comment]
For Javascript, I would suggest to use Standard instead (https://standardjs.com/). Bloody simple to set up, and comes with a lot of tools to ensure proper use. Well integrated into editors as well…

**Comment by bwbohl** [comment]
standardjs apparently also seems to be used by https://github.com/super-linter/super-linter – a tool I would very much like to use in all linting and formatting contexts.

**Comment by bwbohl** [comment]
super-linter would cover the following languages that are being used in Edirom Online:
* CSS
* HTML
* XML (--> XSLT?)

Unfortunately, I can't find good or up-to-date XQuery formatters…

**Comment by krHERO** [comment]
as mentioned already in a [comment](https://github.com/Edirom/Edirom-Online/issues/227#issuecomment-2230777932) in #227  i would like to see the styleguide in a separate file from CONTRIBUTING.md. at the moment content regarding styleguides is living in [CONTRIBUTING.md](https://github.com/Edirom/Edirom-Online/blob/develop/CONTRIBUTING.md). I want to support the suggestion from @riedde in #227 to put (only) information how to contribute to this repository into this file.

**Comment by krHERO** [comment]
closed with https://github.com/Edirom/Edirom-Online/pull/404
of course the file would benefit from more content, but it is a good starting point.
