### ISSUE TITLE
Facsimile-View with TEI-Documents

### ISSUE THREAD

**Issue by obertsalome** [Edirom/Edirom-Online#339]
I have a source encoded in a TEI-Document which can not be displayed by the Edirom: in the split-view the encoded transcription can be displayed but unfortunately not the Facsimile. As @nikobeer told me it's a problem with IIIF – so my source is encoded correctly and can be e.g. displayed with a MEI-Document.

```xml
<facsimile>
        <surface n="1" xml:id="keyRegisterpage1">
               <graphic type="facsimile" url="https://content.staatsbibliothek-berlin.de/dc/826726860-0005" width="1632" height="2200"/>
        </surface>
</facsimile>
```

I kindly ask you to make this rendering possible.

**Comment by nikobeer** [comment]
It "seems" to be a problem with IIIF. There is a IIIF URL in the graphics tag. In the resulting html image tag the href attribute contains only digilib prameters without any URL.

**Comment by obertsalome** [comment]
Dear developers, is there some kind of update already?
