### ISSUE TITLE
Set-up first draft of coding guidelines XQuery

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#359]
see [CONTRIBUTING.md](https://github.com/Edirom/Edirom-Online/blob/78d4d323a5f3c817a41b97bcbc0896e75b1b3d09/CONTRIBUTING.md)

**Comment by krHERO** [comment]
this issue seems to duplicate a sub-task of #336
for this reason and because no issue was commited yet referencing this issue and no further description or comment was added, it will be closed. the work of setting up coding guidelines for XQuery can be tracked in #336 along with other languages.
