### ISSUE TITLE
Description of XML-View

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online#36]
I have changed the label of the menu button 'line #' to 'Line #'. See commit d92b30f. Should this be reflected in the help?

**Comment by bwbohl** [comment]
The help draws program-specific button labels etc. from the respective lang-file in "Edirom-Online/add/data/locale/" for this case the entry with the key 'view.window.xmlView_showLineNumbers.label' would be applied. A change there would be reflected in the help.

**Comment by nikobeer** [comment]
Ok, than we could close this issue.
