### ISSUE TITLE
`source:isSource` fails due to changed meiversion pattern

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#360]
https://github.com/Edirom/Edirom-Online/blob/600f11b225c0d3463696df5798669b47e42623f6/add/data/xqm/source.xqm#L36-L51

This function was created in the belief that `@meiversion` would stick to the three-digit server pattern, but it didn’t. Consequently, the test will fail for any `5.0` MEI files.

**Comment by musicEnfanthen** [comment]
@bwbohl Should be an easy change to `(([4-9])|(\d+[0-9]))\.\d+(\.\d+)?(-dev)?` making the third digit incl. dot only optional.

**Comment by musicEnfanthen** [comment]
Seems that has been fixed already in a8c0994f1f26ff81ea16a655f56f6969a0174809
