### ISSUE TITLE
TextFacsimileSplitView: TEI Facsimile not loading

### ISSUE THREAD

**Issue by riedde** [Edirom/Edirom-Online#370]
The TEI facsimile view was fixed at #356 #339
Maybe a side-effect

**Comment by riedde** [comment]
@bwbohl seems that the FacsimileView is renewed now, but the similar code for the TextFacsimileSplitView needs the same. I tried it, but my skills on this are not too bad to manage.

**Comment by krHERO** [comment]
@bwbohl and @nikobeer could you please provide some more information about this isse and what already was happening. could especially some information regarding openseadragon be helpful?

**Comment by obertsalome** [comment]
The views of text and facsimile are working separately, but the split view of both text and facsimile is not working because the facsimile is not displayed:
![FacsimileOnly](https://github.com/Edirom/Edirom-Online/assets/43742700/8c2bed33-86f4-4b4d-b268-7e530cff56b8)
![TextOnly](https://github.com/Edirom/Edirom-Online/assets/43742700/43deb98d-099d-4e81-bf00-1fe9280dbbf8)
![SplitView](https://github.com/Edirom/Edirom-Online/assets/43742700/8bce996c-1eee-46c3-a807-fe6baedb4a7c)

**Comment by riedde** [comment]
Side comment concerning tei-facsimileView: There is an Issue in the TaMuDi-Project to have the svg overlays also in TEI-facsimiles and not only in the (mei) sourceView. When the facsimile view is touched it can be thought about activating the overlays there. I'm willing to help.

**Comment by Diginaut** [comment]
After comparing @bwbohl changes in `FacsimileViewer.js` for a similar error maybe `view.setImageSet(pages);` in line 66 of `TextFacsimileSplitView.js` has to be changed to `me.pagesLoaded(pages, view);`?

**Comment by musicEnfanthen** [comment]
@obertsalome Is this facsimile also referenced via a IIIF-Uri like in the example in #339 ?

**Comment by bwbohl** [comment]
@Diginaut did you test this?

Als the probelm ist that the split view is missing a statement about openSeadragon as viewer

**Comment by musicEnfanthen** [comment]
@Diginaut I guess you will need to add the definition of pagesLoaded at the bottom as well, like in https://github.com/Edirom/Edirom-Online/blob/9121944b02f86ec178e9547b9334e0ee29f9a4c1/app/controller/window/text/FacsimileView.js#L89-L91

**Comment by musicEnfanthen** [comment]
And yes, I agree with @bwbohl that it looks like IIIF viewer is missing in https://github.com/Edirom/Edirom-Online/blob/develop/app/view/window/text/TextFacsimileSplitView.js . 

Cf. https://github.com/Edirom/Edirom-Online/blob/develop/app/view/window/text/FacsimileView.js

**Comment by Diginaut** [comment]
@musicEnfanthen Thanks for the hint. I will have a look at this and try to implement the OpenSeadragon for the TextFaksimileSplitView.

**Comment by obertsalome** [comment]
> @obertsalome Is this facsimile also referenced via a IIIF-Uri like in the example in #339 ?

Yes, e.g.:
```xml
<facsimile>
        <surface n="I">
                <graphic xml:id="libretto-edition_page_i" url="https://content.staatsbibliothek-berlin.de/dc/1832534529-0001" height="2721px" width="2283px"/>
            </surface>
</facsimile>
```

**Comment by bwbohl** [comment]
> And yes, I agree with @bwbohl that it looks like IIIF viewer is missing in https://github.com/Edirom/Edirom-Online/blob/develop/app/view/window/text/TextFacsimileSplitView.js .
> 
> Cf. https://github.com/Edirom/Edirom-Online/blob/develop/app/view/window/text/FacsimileView.js

yeah, thx, already on it since the online meeting ;-)

**Comment by bwbohl** [comment]
cf. https://github.com/Edirom/Edirom-Online/tree/fix/339-facsimile-view-with-tei-documents

**Comment by bwbohl** [comment]
Ok, principally I got it working but here are some prerequisites that have to be met, before the TextFacsimileSplitView will be available for your text:

- #TextFacsimileSplitView will be available if the XML file
  - `getLinkTarget.xql`: `exists($doc//tei:facsimile//tei:graphic) and exists($doc//tei:pb[@facs])`
    - is in the TEI namespace,
    - has a `tei:facsimile` tree with at least one `tei:graphic` and
    - contains at least one `tei:pb` with a `@facs` attribute
  - but the text will only be properly rendered if
	- getText.qxl:
		- there is at least a second `tei:pb` following the one associated with your page
		- the `tei:pb` elements have `@n` attributes encoded

**Comment by bwbohl** [comment]
![Screenshot 2024-07-03 at 16 33 05](https://github.com/Edirom/Edirom-Online/assets/2430401/9ea83f95-b110-4933-8eee-a7b02ede7962)

**Comment by bwbohl** [comment]
@obertsalome and @peterstadler please test, you can download a deployable Edirom Online with this fix from the Action run at : https://github.com/Edirom/Edirom-Online/actions/runs/9780399110/artifacts/1664499941

**Comment by obertsalome** [comment]
@bwbohl: It got worse 😢 now only the facsimile-view is working...

**Comment by musicEnfanthen** [comment]
@obertsalome Could you share a minimal XML file that can be used for testing?

**Comment by bwbohl** [comment]
for me it is working, so yes, a minimal XML example would be appreciated

**Comment by bwbohl** [comment]
@Diginaut, did your pagesLoaded function fix the issue for you?
