### ISSUE TITLE
Add "About Edirom"

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#381]
Add a modal or window with information about authors, license and release of the Edirom Online

- [ ] #213

**Comment by bwbohl** [comment]
and the version currently deployed

**Comment by bwbohl** [comment]
ping @krHERO & @roewenstrunk  any news on this?

**Comment by bwbohl** [comment]
could also cover #213

**Comment by daniel-jettka** [comment]
first preparations done...

Infos can go here: app/view/window/about/AboutWindow.js

**Comment by daniel-jettka** [comment]
fetching info from CITATION.cff

![image](https://github.com/user-attachments/assets/6779aceb-cc26-4b30-b88f-d22a8274fd4a)
