### ISSUE TITLE
[ftr] add mission statement to Readme 

### ISSUE THREAD

**Issue by peterstadler** [Edirom/Edirom-Online#399]
This is not a technical issue, but rather to improve the documentation.

When you hit the "landing page" of the Edirom Online repo at Github, the Readme is automatically displayed (by GitHub). So, this is the very first information that users will get and thus should contain more details and context regarding the project. Here are some proposals:

* the first paragraph should be a short mission statement: overall goals, field of action, organizational background, visions, etc.
* Next, there should be show cases with images and pointers to existing edirom online editions, e.g. [Bargheer](https://bargheer.edirom.de/index.html), [Webers Klarinettenquintett](https://klarinettenquintett.weber-gesamtausgabe.de/)

… there might be more

**Comment by krHERO** [comment]
hi @peterstadler thanks for opening this issue. in the edirom online reloaded project we are also working on the improvement of "building communities". regarding this topic i started with creating templates for issues with [PR395](https://github.com/Edirom/Edirom-Online/pull/395). one of the next steps is updating the [contributing.md](https://github.com/Edirom/Edirom-Online/blob/develop/CONTRIBUTING.md) (for some discussion see #227) and also updating the [readme.md](https://github.com/Edirom/Edirom-Online/blob/develop/README.md) is on the agenda (started already to search and review readme templates). 
so we already have an issue here to reference our commits to.

we could use this isse to collect content we want to have in the readme.md starting with your suggestions

- [ ] first paragraph: should be a short mission statement: overall goals, field of action, organizational background, visions, etc.
- [ ] show cases with images and pointers to existing edirom online editions, e.g. [Bargheer](https://bargheer.edirom.de/index.html), [Webers Klarinettenquintett](https://klarinettenquintett.weber-gesamtausgabe.de/)
