### ISSUE TITLE
Tooltip size too small

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online#40]
Tooltips are triggered only in the upper left corner of buttons.

**Comment by bwbohl** [comment]
I cannot reproduce this behaviour on the current develop branch state.

**Comment by bwbohl** [comment]
But I think it was not about annotation tooltips but also about the toolbar buttons, but also there I cannot reproduce.

**Comment by bwbohl** [comment]
This does not happen with the Edirom from develop, maybe check your lang files against those in the main repo, if I remember correctly I replaced all whitespaces with no-break whitespaces.

**Comment by bwbohl** [comment]
The triggering area is definitely fixed, thus renaming issue.

**Comment by bwbohl** [comment]
@nikobeer, from my experience, this can be OS- and browser-dependent. Could you please provide which platforms you encountered this error on?

I could not reproduce the error in Chrome v129.0.6668.60 on MacOS v12.7.5.

**Comment by daniel-jettka** [comment]
This is how it looks like in Chrome 129.0.6668.100 on Linux Mint 20.1

![image](https://github.com/user-attachments/assets/d306e7a5-81f7-4347-a2bc-84d570547527)

**Comment by bwbohl** [comment]
> This is how it looks like in Chrome 129.0.6668.100 on Linux Mint 20.1


Just as it should, thanks!

**Comment by bwbohl** [comment]
@nikobeer any chance you provide some OS and browser details? Otherwise I tend to closing this and wait for future reports on similar issues.

**Comment by nikobeer** [comment]
@bwbohl You can close it. Seems to be a bug in our own fork.
