### ISSUE TITLE
SourceView: go to measure… function returns wrong measure

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#432]
If the edition uses `@n` for a technical enumeration of `mei:measure` and `@label` for a semantical naming of the measures, which is, e.g., needed if a measure breaks across systems, using the "go to measure…" function in sourceView returns the wrong measure, because the function for finding the correct measure-ID relies on `@n`.

https://github.com/Edirom/Edirom-Online/blob/95a76e84195caa7205bcc4eceadd68c0611ccc4c/add/data/xql/getMeasurePage.xql#L27

**Comment by peterstadler** [comment]
Is there any idea on how to fix this?

**Comment by bwbohl** [comment]
> Is there any idea on how to fix this?

Maybe something like?

```xquery
 (($mei/id($movementId)//mei:measure[@label eq $measureIdName], $mei/id($movementId)//mei:measure[@n eq $measureIdName])[1]) 
 ```

**Comment by bwbohl** [comment]
The above could provide a quick fix, but…

On a second thought, maybe thiw would not be ideal in cases of measures breaking across systems (and maybe even pages) because then it would only return the first  part of the measure (the first measure with a matching `@label`).

This needs a more detailed look and a proper refactoring would be the ideal, i.e.:

1. This query is called from 3 places

   and was adjusted each time a new functionality was added to Edirom Online.
    I think this is in the order of implementation history:

   1. `app/controller/window/source/SourceView.js` from the function `onGotoMeasureByName` (which this issue originally was about)
      
      parameters:
         * id: view.uri, --> xmldb:uri pointing to the MEI to query
         * measure: measure, --> user input from GotoMsg form field (type: string)
         * movementId: movementId 
   
   2.  `app/controller/window/source/MeasureBasedView.js`
      from the function `onShowMeasure: function(view, uri, measureId, count)`
      
       parameters:
         * id: uri, --> xmldb:uri pointing to the MEI to query
         * measure: measureId,  --> the xml:id of the first measure to show
         * measureCount: count  --> the number of measures to show starting from `measureId`
   
   4. `app/controller/window/source/VerovioView.js`  from the function `onGotoMeasureByName`
      
      parameters:
         * id: view.uri, --> xmldb:uri pointing to the MEI to query
         * measure: measure,
         * movementId: movementId
   
   While the `id` parameter is always some xmldb:uri pointing to the MEI file, `measure` can be either a completely uncontrolled string OR an xml:id, `movementId` is used in (1.) context to provide a context for retrieving the measure by 'name' and `measureCount` is used in (2.) to accomodate the option of MeasureBasedView to show multiple measures starting from the selected one. (I skipped checking the details for (3.) for now)

All in all I think a bigger refactoring would be good in this context but for now a small fix should be tested.

**Comment by bwbohl** [comment]
This also touches the context of #102

**Comment by hizclick** [comment]
I tested the quick fix by the default example edition, and it works, but the commit needs more tests for the other scenarios.

**Comment by peterstadler** [comment]
Hi @hizclick , if you're done with the implementation of the fix please create a PR from your branch. This signals that others should have a look and review your changes.
