### ISSUE TITLE
Add a centralised concept for using / retrieving data from current edition’s collection

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#437]
This issue serves as a collection point for issues dealing with data from the active entity collection. Please feel free to add the respective issues as tasks below.

Several issues are open around some XQueries that use a wrong database path to retrieve data relevant to the `activeEdition`. Instead of creating individual fixes in those queries, we should centrally define a function for retrieving data from the `activeEdition` context and use it where applicable.

- [x] #83
- [x] #156 
- [x] #240 
- [x] #453

**Comment by peterstadler** [comment]
There's a new function https://github.com/Edirom/Edirom-Online/blob/0b6c9f3df06058e496f73eafbd29fb963e2cf8d6/add/data/xqm/edition.xqm#L194-L207 

@bwbohl  does this function provide what you're looking for?

**Comment by hizclick** [comment]
All the collections for this issue are closed.

**Comment by peterstadler** [comment]
I think the idea of this ticket was not to only collect several issues but to "Add a centralised concept for using / retrieving data from current edition’s collection".

If @bwbohl agrees that the function `edition:collection#1` does that job we'll then need to replace all (relevant) occurrences of direct `collection` calls with this new function. I'm preparing a PR for that.
