### ISSUE TITLE
[BUG] Edirom fails when no edition lang is defined

### ISSUE THREAD

**Issue by riedde** [Edirom/Edirom-Online#441]
**Describe the problem**
When no default lang is defined in the data the edirom fails. I think the problem occurs here https://github.com/Edirom/Edirom-Online/blob/8742faa6240acbd6fd05c58cbe9b1c1f7ef02eec/add/data/xqm/edition.xqm#L76

**To Reproduce**
Delete the language from the preferences and/or the edirom-edition-file.

**Expected behavior**
If no lang is defined the edirom should use the default lang of the software (https://github.com/Edirom/Edirom-Online/blob/8742faa6240acbd6fd05c58cbe9b1c1f7ef02eec/add/data/prefs/edirom-prefs.xml#L25). I remember, that we already fixed this but maybe not for this case.

**Data**
Use any data and play with the lang definition.

**Edirom information**
 - Version on develop (2024-10-11)

**Environment information**
- Standard

**Comment by peterstadler** [comment]
I think it's rather this function that should be fixed:
https://github.com/Edirom/Edirom-Online/blob/8742faa6240acbd6fd05c58cbe9b1c1f7ef02eec/add/data/xqm/util.xqm#L305-L316

… since `eutil:getLanguage#1` might return an empty string.

My suggestion would be to hard code a default value as the last else case to make sure to always return something sensible.

When at it, I think we should modify this function to not only *get* but also *set* the language. Currently, this is only done at index.xql at https://github.com/Edirom/Edirom-Online/blob/c96595da78b482f87a4fd67f7a75e09062b11dd6/add/controller.xql#L38
but I think we should be able to set the language more dynamically (without reloading the page).

**Comment by riedde** [comment]
Setting a language would be good.
I wanted to fix the other function because there also isn‘t a default. If the preferences return a default the function you mentioned should never return empty().

But we can implement a default for both.

**Comment by bwbohl** [comment]
This is to some degree also connected to the undefinedness of prefs.xml.
If we introduce a proper schema for that, we could require `application_language` to be set.

Nevertheless we should first define where a 'preferred', 'default' or 'fallback' language-setting should come from.

I see two cases here:

1. First visitors
2. Returning visitors

In both cases the question should be: Is it the user or the application who decides. And we should become clear about the fact that we have two areas of language: the GUI and the edition’s contents. So we must also talk about behaviour of the app when e.g. contents do not support the selected langugage or not fully support the selected language.

Outside of that:
@peterstadler’s feature request for changing language setting without reloading should definitely be targeted.

btw: there was an idea for offering user prefs setting s in the past:

https://github.com/Edirom/Edirom-Online/blob/56d0f0ebdf033924bf91351d391a1da4c3d9908b/app/view/desktop/TaskBar.js#L76

**Comment by riedde** [comment]
I got the point where it fails. working on that

**Comment by riedde** [comment]
Just a small comment

> This is to some degree also connected to the undefinedness of prefs.xml.
If we introduce a proper schema for that, we could require application_language to be set.

`application_language` is always set at edirom-prefs.xml, but this isn't called. There is a fallback that the sofware default prefs are called if no other prefs are defined, but not if a single value is missing. I already have a solution, but not pushed yet. This is because a cookie-lookup has been integrated some time ago (RWA-merge) and this cookie is always set but sometimes empty. The conditional has to be updated and I try to fix both.

**Comment by bwbohl** [comment]
Ah forgot about the fallback prefs… Maybe we should check the cookie and delete it if empty?

**Comment by riedde** [comment]
@bwbohl I would propose not to create the lang cookie, because this was an RWA-artifact. It will always be empty.
