### ISSUE TITLE
[BUG] CSS regression

### ISSUE THREAD

**Issue by peterstadler** [Edirom/Edirom-Online#451]
## Describe the problem

When reviewing the PR #445 with the clarinet quintet data it occurred to me that some CSS had changed. At first I blamed this PR but then I realized that it must have been introduced at some earlier stage since #444 also showed this behavior. 

## To Reproduce
1. build Edirom Online from dev
2. load clarinet data from pipeline build at https://git.uni-paderborn.de/wega/klarinettenquintett-edirom
3. load both xar packages into a fresh existdb
4. launch Edirom Online
5. open "Editionsbericht"

### Expected behavior

running with v1.0.0-beta.5
![Bildschirmfoto 2024-10-15 um 10 10 17](https://github.com/user-attachments/assets/ac532782-da12-4310-8ed7-bf8026a1626c)

### how it looks like 

running with current dev
![Bildschirmfoto 2024-10-15 um 10 11 29](https://github.com/user-attachments/assets/cb5e1f03-7540-4db0-8485-50d527bc7b1e)

**Comment by bwbohl** [comment]
maybe it’s connected to the update of the TEI Stylesheets (#371 )?

**Comment by bwbohl** [comment]
Unfortunately  I cannot reproduce this at the moment, all looks fine in my instance…

**Comment by bwbohl** [comment]
Meanwhile I can confirm this, too…

We should do a proper cleanup of `resources/css/todo.css`
Having it at all was a bad idea in the first place; it came into existence for quick css development but the rules defines should always be properly incorporated in the SASS definitions. Moreover, with the `additional_css_path` preference property it is easy to temporarily add any css file in the database for such purposes.

**Comment by peterstadler** [comment]
There's a similar CSS issue in the Search window, see https://github.com/Edirom/Edirom-Online/pull/463#issuecomment-2465041218

**Comment by daniel-jettka** [comment]
I tried to fix the indentation. @peterstadler Could you check? I mean the heading looks different too... Is this a bigger thing or enough for now to change indentation?

**Comment by peterstadler** [comment]
I think we need to investigate a bit more regarding the root cause of this change. I just compared the CSS files from the [old](https://klarinettenquintett.weber-gesamtausgabe.de/index.html) and the current version:  the old one loads a file `/apps/weber-klarinettenquintett-eol-emeritus/resources/css/main.css`, i.e. from the data collection, not from the Edirom Online collection. Hence, it seems to me that the loading of project specific CSS files fails somehow?!

**Comment by roewenstrunk** [comment]
In `index.xql` line 23 (https://github.com/Edirom/Edirom-Online/blob/fc3baf87c49e71a1207f6039ad29bdc80af325bc/add/index.xql#L23) there should not be an if clause. You will always want to find the `editionURI`.

**Comment by daniel-jettka** [comment]
https://github.com/Edirom/Edirom-Online/blob/4a5996475f043aa70b153a38101ee5fee9a454e5/add/data/xqm/edition.xqm#L149

Right, it always returns a path to a edition.

**Comment by daniel-jettka** [comment]
> In `index.xql` line 23
> 
> https://github.com/Edirom/Edirom-Online/blob/fc3baf87c49e71a1207f6039ad29bdc80af325bc/add/index.xql#L23
> there should not be an if clause. You will always want to find the `editionURI`.
> 
> Then the project specific css is loaded again.

We have been there before...

https://github.com/Edirom/Edirom-Online/commit/ce11d08e84574f392d8192ac9266c35f70828b92#diff-80de71d6521dca34527afd883208d84dea282e9ea5c0c8e7ebf234df8c0a286eL23
