### ISSUE TITLE
[BUG] old code in getAnnotationsInText.xql

### ISSUE THREAD

**Issue by roewenstrunk** [Edirom/Edirom-Online#453]
**Describe the problem**

In `getAnnotationsInText.xql` we still search in `/db/contents` and are not using the new way for priorities and categories in annotations.

**To Reproduce**

We made up code for the review of #419. So it is not easy to reproduce.

** To Do **

We have to search for annotations in the collection (see https://github.com/Edirom/Edirom-Online/blob/00a1f269a8b50b46bcccbb9c45f9c57b175bc11c/add/data/xql/getAnnotationsInText.xql#L35) pointed to in `$edition` (needs to be requested like in https://github.com/Edirom/Edirom-Online/blob/00a1f269a8b50b46bcccbb9c45f9c57b175bc11c/add/data/xql/getAnnotationsOnPage.xql#L219). Than copy the priority and categories method from https://github.com/Edirom/Edirom-Online/blob/00a1f269a8b50b46bcccbb9c45f9c57b175bc11c/add/data/xql/getAnnotationsOnPage.xql#L66 for https://github.com/Edirom/Edirom-Online/blob/00a1f269a8b50b46bcccbb9c45f9c57b175bc11c/add/data/xql/getAnnotationsInText.xql#L43

**Comment by peterstadler** [comment]
@roewenstrunk is this a duplicate of #240 ?

**Comment by roewenstrunk** [comment]
> @roewenstrunk is this a duplicate of #240 ?

Yes, this is a duplicate. My bad…

**Comment by peterstadler** [comment]
Ok, so let's close the issue here and follow it at #240
