### ISSUE TITLE
[BUG] parts display

### ISSUE THREAD

**Issue by AndreasMunzmay** [Edirom/Edirom-Online#459]
**Describe the problem**
orchestral / choral parts are not displayed properly in Edirom Online, neither via the "Go to" menu nor in the measure based view nor within the critical notes
 
**To Reproduce**

1. Go to https://openedirom.lilienteich.de/exist/apps/Edirom-Online/index.html?edition=edition-LindP&lang=en
2. Open Source A3 or A4
3. Try to navigate to whatever mdiv in whatever part
4. OR use the Concordance Navigator and try to navigate to whatever measure in A3 or A4
5. OR open a critical note that refers to a specific movement/bar of a specific instrument (e.g. note 230, 231, 232…) 

**Expected behavior**
correct navigation into parts and the mdivs (and measures) contained in the parts

NB: MEI's nesting (parts inside mdivs) is the opposite of the 'real world oriented Edirom source display (parts containing some, but not necessarily all, movements of the work) --> see [stimmen.pdf](https://github.com/user-attachments/files/17649757/stimmen.pdf)

**Data**
https://git.uni-paderborn.de/kio/open-faust/-/tree/main/content/sources?ref_type=heads

**Additional context**
Worked perfectly (yet very slowly) in the 'OPERA' Edirom

**Comment by nikobeer** [comment]
Solved with @bwbohl and @feuerbart. The data was not ready.
