### ISSUE TITLE
[ftr] Enhance/update help page

### ISSUE THREAD

**Issue by daniel-jettka** [Edirom/Edirom-Online#471]
**Is your feature request related to a problem? Please describe.**
The help pages are somewhat outdated and need some review

**Describe the solution you'd like**
Work on add/help - https://github.com/Edirom/Edirom-Online/tree/f8abab67bd86cb055859be8fdb9965602477e854/add/help

**Describe alternatives you've considered**
remove help - not an option

**Additional context**
./.

**Comment by daniel-jettka** [comment]
related issues

- [ ] #24 
- [ ] #25 
- [ ] #26 
- [ ] #27 
- [ ] #28 
- [ ] #29 
- [ ] #30 
- [ ] #31 
- [ ] #32

**Comment by krHERO** [comment]
closed with #497
