### ISSUE TITLE
[BUG] remove foreign tags from Edirom Online git history

### ISSUE THREAD

**Issue by peterstadler** [Edirom/Edirom-Online#473]
**Describe the problem**
There are several tags in the Edirom Online git history that seem to originate from forks and taint our history. E.g., looking at https://github.com/Edirom/Edirom-Online/tags there is a version [1.5](https://github.com/Edirom/Edirom-Online/releases/tag/1.5) tagging commit 0ba1b70 which is not available: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

My proposal would be to look through the tags and remove those with missing commits.

**Comment by daniel-jettka** [comment]
> ### following tags do NOT have the message regarding missing commits, but they are also quite sure not part of the edirom-online repo
> 
> @roewenstrunk @peterstadler what do you think? compared to the tags of the edirom-online releases, this tags are not from this repo and i tend to also delete them. Although i do not know, why they "pretend" to be part of edirom-online repo...
> 
>     * [1.4.1](https://github.com/Edirom/Edirom-Online/releases/tag/1.4.1) / [d06c79b](https://github.com/Edirom/Edirom-Online/commit/d06c79bdbaf3683c8ce94cf0c61d59c6733b8384) see especially  [reger-content](https://github.com/Edirom/Edirom-Online/commit/d06c79bdbaf3683c8ce94cf0c61d59c6733b8384#diff-a4f12696bcaf800779ffddc7113b0325f7ca8f271db0d6375f95a6b94127b1d7R39)
> 
>     * [version-rwaVol_II-8.1](https://github.com/Edirom/Edirom-Online/releases/tag/version-rwaVol_II-8.1) / [fe9f275](https://github.com/Edirom/Edirom-Online/commit/fe9f275f1878c63abe03fc3efa9d9f6ba033e21a)
> 
>     * [version-rwaVol_II-8](https://github.com/Edirom/Edirom-Online/releases/tag/version-rwaVol_II-8) / [020e262](https://github.com/Edirom/Edirom-Online/commit/020e262f79e8d9b1e541aa2776a4f9dac5841c97)
> 
>     * [version-rwaVol_II-1](https://github.com/Edirom/Edirom-Online/releases/tag/version-rwaVol_II-1) / [3e16dc3](https://github.com/Edirom/Edirom-Online/commit/3e16dc3c87674d08dea7e193a446b173bfd5c4e0)

Those were merged into develop...

* [1.4.1](https://github.com/Edirom/Edirom-Online/releases/tag/1.4.1) / PR #166 
* [version-rwaVol_II-8.1](https://github.com/Edirom/Edirom-Online/releases/tag/version-rwaVol_II-8.1) / PR #120 
* [version-rwaVol_II-8](https://github.com/Edirom/Edirom-Online/releases/tag/version-rwaVol_II-8) / PR #120 
* [version-rwaVol_II-1](https://github.com/Edirom/Edirom-Online/releases/tag/version-rwaVol_II-1) / PR #120 

I would also delete those tags.

**Comment by krHERO** [comment]
thanks for your feedback, i did also delete the 4 suggested tags (from mri-repo). meanwhile i looked for the mri-tags and all deleted [tags](https://github.com/Max-Reger-Institut/Edirom-Online/tags) came from commits to mri-repo

**Comment by daniel-jettka** [comment]
tags are still there or there again... this happened before, there was a similar issue before: #334

**Comment by daniel-jettka** [comment]
_Tag deleted keeps coming back even after deletion locally and remotely.

You could be in a scenario where you are sure you deleted certain git tags both locally and remotely, but you still see them after some time for unknown reasons.

This could happen when you have other collaborators on a git repository. To resolve this, always ensure you communicate the deletion of a tag so that others can update their local repositories. Better still, set up branch protection._

https://kodekloud.com/blog/git-delete-tag/

**Comment by peterstadler** [comment]
It's probably not a "foreign" tag so bear with me for reopening the issue but I believe tag "v1.1.0-alpha" is erroneous, too. It has the same message and date as v1.0.0-alpha which leads me to assume it was mistakenly created? Maybe @bwbohl knows?
![Bildschirmfoto 2024-12-05 um 16 28 27](https://github.com/user-attachments/assets/7a0010f1-1bdd-4e86-89eb-fc277476d98c)

**Comment by krHERO** [comment]
> It's probably not a "foreign" tag so bear with me for reopening the issue but I believe tag "v1.1.0-alpha" is erroneous, too. It has the same message and date as v1.0.0-alpha which leads me to assume it was mistakenly created? Maybe [@bwbohl](https://github.com/bwbohl) knows? ![Bildschirmfoto 2024-12-05 um 16 28 27](https://github.com/user-attachments/assets/7a0010f1-1bdd-4e86-89eb-fc277476d98c)

ping @bwbohl do you know?

**Comment by roewenstrunk** [comment]
Erroneous tag v.1.1.0-alpha deleted. Metadata of Zenodo entry for v.1.0.0-alpha (https://zenodo.org/records/6395227) corrected
