### ISSUE TITLE
[ftr] Repair & enhance Zenodo integration

### ISSUE THREAD

**Issue by daniel-jettka** [Edirom/Edirom-Online#475]
**Is your feature request related to a problem? Please describe.**
Version 1.0.0-beta.6 was not published automatically to Zenodo - has to be repaired.
Other Zenodo related features were suggested in #113 - these are moved here.

**Describe the solution you'd like**
- working Zenodo integration / pipeline
- add build artifacts to the Zenodo publications

**Describe alternatives you've considered**
Manual publication on Zenodo - not desirable

**Additional context**
failed deliveries to Zenodo: https://github.com/Edirom/Edirom-Online/settings/hooks/315777526?tab=deliveries

**Comment by daniel-jettka** [comment]
Related problem:

A bunch of dev releases were unintentionally published to Zenodo. https://zenodo.org/search?q=parent.id%3A5347861&f=allversions%3Atrue&l=list&p=1&s=10&sort=version

I am contacting Zenodo via https://zenodo.org/support to remove those.

**Comment by bwbohl** [comment]
Oh that is unpretty, we should deactivate the dev tag and release creation to avoid this in the future

**Comment by bwbohl** [comment]
cf. https://github.com/zenodo/zenodo/issues/1413

**Comment by krHERO** [comment]
@bwbohl we had a little discussion with the reloaded project. yes, please deactivate the dev tag and also deactivate the release creation. the issue can be closed afterwards

**Comment by peterstadler** [comment]
You can find out about the owner of a zenodo repo from the "share" button (if you have manage rights):
![Bildschirmfoto 2024-12-05 um 16 37 12](https://github.com/user-attachments/assets/3d494239-c48a-40f0-b31f-877d0db33082)
So @roewenstrunk is the owner

**Comment by roewenstrunk** [comment]
I wrote a request today

**Comment by roewenstrunk** [comment]
The records are removed now
