### ISSUE TITLE
Remove FreiDi-specific contents

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online#49]
- Application title
- logos
  …

**Comment by krHERO** [comment]
@nikobeer can you check please, if this issue can be closed? thanks :)

**Comment by nikobeer** [comment]
As @bwbohl linked it to #239, I think this should stay open…

**Comment by krHERO** [comment]
in the current develop-branch, especially latest pre-release [v1.0.0-beta.6](https://github.com/Edirom/Edirom-Online/releases/tag/v1.0.0-beta.6) there is no freidi in the title anymore neither is the logo still displayed. it is the vife logo with "edirom online" next to it. i did not searched, when freidi-logo was deleted, but eg the vife-logo was added with this [commit](https://github.com/Edirom/Edirom-Online/commit/39b93a83cb97dd9b40f410fbab4ed8fcc6d8392e)
plus yes, we have the #239 as mentioned by niko to take care of fork-developments. although the #239 wants to take care of adding stuff from project-forks, while this one wanted to delete project-specific stuff.
