### ISSUE TITLE
[BUG] Edirom is unreachable without Cookies

### ISSUE THREAD

**Issue by DennisFriedl** [Edirom/Edirom-Online#504]
**Describe the problem**
In the current `dev` branch the Edirom is not reachable with the error "Uncaught TypeError: me.preferences is undefined". 

**To Reproduce**
1. Open an Edirom
2. Open the Developer Tools, delete all Cookies of the Edirom
3. Reload

**Context**
- the problem was introduced with [#fd45a49](https://github.com/Edirom/Edirom-Online/commit/fd45a49c328ecc105d2feb14372a1bd3e1d7f684)
- reintroducing `<set-header name="Set-Cookie" value="edirom-language={$langVal}" />` fixes the error but is a cookie necessary?

**Comment by peterstadler** [comment]
I can confirm the issue (just for the record)

**Comment by Diginaut** [comment]
It seems that the language cannot be read from the preferences file if no cookie is set. Presumably this applies to the preferences query in general.

**Comment by krHERO** [comment]
@feuerbart modify function getLanguage in LanguageController.js
thank you
