### ISSUE TITLE
documentation of help concept

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#56]

**Comment by krHERO** [comment]
i don`t see the need for this 9 year old issue (anymore). 
we have a short description in the readme.md ho to set up the edirom-online olus a subchapter regarding documentation where the content of /docs is linked. with [PR472](https://github.com/Edirom/Edirom-Online/pull/472) the (partly outdated) docu from the wiki moved to this /docs folder and was revisited and updated.
will close this issue
