### ISSUE TITLE
Sencha Cmd version

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#58]
The Wiki says I should download Sencha Cmd 4.0.4.84 the current version is 5 and the only older one for download is 5.0.5 will this work?

Maybe we should not be too precise in these kinds of documentation, it makes them outdated quite fast!

**Comment by nikobeer** [comment]
My experience: any other (newer) version of Sencha Cmd won't work. Therefore, I decided to name precise versions to avoid such problems.

**Comment by bwbohl** [comment]
ok, if I recall correctly everything built fine under 5.0.5 on my win7; this definitely needs more testing...

**Comment by bwbohl** [comment]
I built EO successfully under macOS Sierra 10.12.2 with Sencha Cmd v6.2.1.29 except a few warnings about the older version that had modified the project, everything wen't fine and the software build was stable, so yes, we could remove the specific version of sencha from the documentation.

**Comment by bwbohl** [comment]
especially as the version specified isn't available for download anymore

**Comment by bwbohl** [comment]
this website gives a nice overview of the Sencha Cmd requirements for building apps with specific Ext JS versions. From todays POV it's rather the Ruby version that might throw problems.
