### ISSUE TITLE
Build process: Where can someone change settings?

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online#60]
Tried to change (file) name of the application package in build.xml. Changes show no effect.

**Comment by nikobeer** [comment]
There are two build.xml files. Sencha Cmd output says it is using /build.xml. But the file actually used is /add/build.xml. Could the first one be deleted?

**Comment by krHERO** [comment]
ping @nikobeer

**Comment by nikobeer** [comment]
Yes.
