### ISSUE TITLE
disable shortcut ESC

### ISSUE THREAD

**Issue by krHERO** [Edirom/Edirom-Online#65]
ESC closes every opened window. Since it is a very helpful shortcut in Finale, it is used very often kind of automatically also in edirom online.
--> could that shortcut be disabled?

**Comment by bwbohl** [comment]
This should be tackled in conjunction with #67 and a possible sprint for implementing shortcuts

**Comment by krHERO** [comment]
will be closed cause content is kind of duplicated with #2
