### ISSUE TITLE
improve navigation "goto"

### ISSUE THREAD

**Issue by krHERO** [Edirom/Edirom-Online#66]
navigation for movements "goto" does not display everything is not working correctly, when handling with a lot of movements. when the list of movements is too long, its even impossible to navigate to the last ones --> replace/improve navigation/scrollbar please

**Comment by bwbohl** [comment]
it might be adviseable to tackle this problem in conjunction with #69

**Comment by krHERO** [comment]
i checked again and can not see or reproduce this. all the movements are visible in a long list of the submenu "goto movement ...". will close this issue.

**Comment by bwbohl** [comment]
Did you check with a list that will overflow your window/screen size?

**Comment by krHERO** [comment]
yes, scrolling is possible if list ist larger than the window. thanks for pointing also to this possibility to check.
