### ISSUE TITLE
feature: change pages by using cursor keys

### ISSUE THREAD

**Issue by krHERO** [Edirom/Edirom-Online#67]
it would be very helpful, if turning pages is possible with cursor keys, in addition to clicking

**Comment by bwbohl** [comment]
this would indeed be a very good enhancement and points our nose to reimplementing keyboard shortcuts in a wider manner...
@nikobeer @roewenstrunk @kepper : could we possibly find a timespan for a sprint to fix this?

**Comment by roewenstrunk** [comment]
Elena is going to take care of the shortcuts. Maybe we could collect some wishes here…

**Comment by krHERO** [comment]
see also #2

**Comment by krHERO** [comment]
will be closed cause content is kind of duplicated with #2
