### ISSUE TITLE
movements and parts in PageBasedView

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online#69]
How was it implemented in the Carus-Version of Edirom-Online?

**Comment by bwbohl** [comment]
that specific edition apparently implemented the necessary menu hard-coded, that is an if-else statement would return the menu needed for a specific source containing parts.

**Comment by bwbohl** [comment]
nevertheless we solved it for **OPERA vol. 2**. Although the Edirom-Online version used for OPERA is older it now is ahead concerning this (and some other) features.

**Comment by bwbohl** [comment]
will you take care of the respective code coming to Edirom-Online main development branch or should I?

**Comment by krHERO** [comment]
@bwbohl @nikobeer did you figure out who wants to take care of this meanwhile?

**Comment by nikobeer** [comment]
Should be solved as all OPERA developments concerning parts have been copied to the RWA Edirom-Online and then reintegrated here.
