### ISSUE TITLE
How to manage different works in one Edirom Online installation

### ISSUE THREAD

**Issue by rklugseder** [Edirom/Edirom-Online#71]
What modifications are necessary to include different Edirom Editions in one Edirom Online installation. Perhaps with a start screen (like in the Reger editions) with the possibility to pre-select a work/composition (= Edirom Edition).

**Comment by bwbohl** [comment]
I think the solution is connected to #90 and might be solved with #96

**Comment by krHERO** [comment]
> I think the solution is connected to #90 and #91 and might be solved with #96

since no further questions occured since bennis answer, i close this issue.

**Comment by bwbohl** [comment]
Just to add: the current develop branch adds a (still ugly) index page that lists the editions installed in the database if you call edirom online without specifying parameters for directly opening a specific edition or work.
