### ISSUE TITLE
Concordance navigator not switching together with the work context

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online#78]
… when work comboBox is activated and work changed with comboBox.

**Comment by nikobeer** [comment]
to activate work comboBox change app/view/desktopTopBar.js l. 74.

**Comment by riedde** [comment]
I have tested this by duplicating the work from the example edition. That worked fine. Maybe it should be tested with an other edition that has more various data.

**Comment by nikobeer** [comment]
We have fixed this for RWA in XUL-Wrapper and electron with @cappelnord. But we are not using edirom work switch anymore. @riedde just duplicating work contexts may not be sufficient to see it working…

**Comment by riedde** [comment]
@nikobeer I have already noticed that ... But I have a new testset with to different works an the concordance navigator is switching with the work content (testet with Chrome Version 99.0.4844.74 (Offizieller Build) (arm64)).
@bwbohl do we need more testing? In the Release branch (#195) the concNav is switching but not working. I reported this to the PR of the release.

**Comment by bwbohl** [comment]
@riedde we fixed this for the 1.0.0-alpha correct? If so please close

**Comment by riedde** [comment]
In my tests for the 1.0.0-alpha this issue doesn't appear. It works. So I'll close this issue.
