### ISSUE TITLE
Sort buttons: calculation of window dimensions and positions

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online#88]
When windows are minimized and one of the sort buttons is pressed the resulting window dimensions and positions are influenced by the number of invisible windows. See screen shots.

![bildschirmfoto 2016-07-14 um 15 07 00 2](https://cloud.githubusercontent.com/assets/2676362/16840379/ab549b2c-49d4-11e6-815d-f8821c0305a9.png)
![bildschirmfoto 2016-07-14 um 15 06 52 2](https://cloud.githubusercontent.com/assets/2676362/16840386/b9b625f0-49d4-11e6-8715-8193f8f6e0bf.png)
![bildschirmfoto 2016-07-14 um 15 06 42 2](https://cloud.githubusercontent.com/assets/2676362/16840392/c04223f6-49d4-11e6-816d-31b9d0dfd209.png)

**Comment by roewenstrunk** [comment]
Problem is fixed in 4355e95b6e2b41cdc7a3b3b85674b66e0cac6e5d in Branch [feature-freidi-integration](https://github.com/Edirom/Edirom-Online/tree/feature-freidi-integrationurl)
