### ISSUE TITLE
Paramter "activeEdition"

### ISSUE THREAD

**Issue by nikobeer** [Edirom/Edirom-Online#90]
In previous versions (like OPERA) it was possible to leave the parameter "activeEdition" in application.js empty and to define it while calling the app.js in index.html like:

`<script type="text/javascript" src="app.js?edition=/db/contents/edition-12345"/>`

This seems not to work anymore?

**Comment by bwbohl** [comment]
@roewenstrunk any ideas?

**Comment by roewenstrunk** [comment]
Please check the pull request #96 and merge
